import {
    type DefinedTypeNode,
    type InstructionAccountNode,
    type InstructionInputValueNode,
    type InstructionNode,
    pascalCase,
    type RootNode,
    type TypeNode,
} from 'codama';

import { OPTIONAL_NODE_KINDS } from '../../../shared/nodes';

/**
 * Generate TypeScript instruction-level types from a Codama IDL.
 */
export function generateInstructionTypes(idl: RootNode): string {
    const programName = pascalCase(idl.program.name);
    const definedTypes = idl.program.definedTypes ?? [];

    let output = `/**
 * Auto-generated instruction types
 * DO NOT EDIT - Generated by @codama/dynamic-instructions generate-instruction-types
 */

import type { Address } from '@solana/addresses';
import type { InstructionsBuilderFn, ResolverFn } from '@codama/dynamic-instructions';

`;

    for (const ix of idl.program.instructions) {
        output += generateInstructionTypeBlock(ix, definedTypes);
    }

    // Aggregate map type
    output += `/**
 * Strongly-typed instruction builders for ${programName}.
 */
export type ${programName}InstructionBuilders = {\n`;

    for (const ix of idl.program.instructions) {
        const typeName = pascalCase(ix.name);
        const eitherSignerAccounts = ix.accounts.filter(acc => acc.isSigner === 'either');
        const resolverNames = collectResolverNames(ix);

        const signersGeneric = eitherSignerAccounts.length > 0 ? `${typeName}Signers` : 'string[]';
        const args = ix.arguments.filter(arg => arg.defaultValueStrategy !== 'omitted');
        const remainingAccountArgs = (ix.remainingAccounts ?? []).filter(ra => ra.value.kind === 'argumentValueNode');
        const hasArgs = args.length > 0 || remainingAccountArgs.length > 0;
        const argsGeneric = hasArgs ? `${typeName}Args` : 'void';
        const accountsGeneric = `${typeName}Accounts`;
        const resolversGeneric = resolverNames.size > 0 ? `, ${typeName}Resolvers` : '';

        output += `    ${ix.name}: InstructionsBuilderFn<${argsGeneric}, ${accountsGeneric}, ${signersGeneric}${resolversGeneric}>;\n`;
    }

    output += '};\n';

    return output;
}

function generateInstructionTypeBlock(ix: InstructionNode, definedTypes: DefinedTypeNode[]): string {
    let output = '';
    const typeName = pascalCase(ix.name);

    // Build args type
    const args = ix.arguments.filter(arg => arg.defaultValueStrategy !== 'omitted');
    const remainingAccountArgs = (ix.remainingAccounts ?? []).filter(ra => ra.value.kind === 'argumentValueNode');
    let argsRef = 'void';
    if (args.length > 0 || remainingAccountArgs.length > 0) {
        const argsInterfaceName = `${typeName}Args`;
        output += `export type ${argsInterfaceName} = {\n`;
        for (const arg of args) {
            const tsType = codamaTypeToTS(arg.type, definedTypes);
            const isOptional = OPTIONAL_NODE_KINDS.includes(arg.type.kind);
            const sep = isOptional ? '?:' : ':';
            output += `    ${arg.name}${sep} ${tsType};\n`;
        }
        for (const ra of remainingAccountArgs) {
            const sep = ra.isOptional ? '?:' : ':';
            output += `    ${ra.value.name}${sep} Address[];\n`;
        }
        output += '};\n\n';
        argsRef = argsInterfaceName;
    }

    // Build accounts type
    const accountsInterfaceName = `${typeName}Accounts`;
    if (ix.accounts.length > 0) {
        output += `export type ${accountsInterfaceName} = {\n`;
        for (const acc of ix.accounts) {
            const omittable = isAccountAutoResolvable(acc) ? '?' : '';
            const type = acc.isOptional ? 'Address | null' : 'Address';
            output += `    ${acc.name}${omittable}: ${type};\n`;
        }
        output += '} & Record<string, Address | null | undefined>;\n\n';
    } else {
        output += `export type ${accountsInterfaceName} = Record<string, Address | null | undefined>;\n\n`;
    }

    // Signers type (only when isSigner: 'either' accounts exist)
    const eitherSignerAccounts = ix.accounts.filter(acc => acc.isSigner === 'either').map(acc => `'${acc.name}'`);
    if (eitherSignerAccounts.length > 0) {
        output += `export type ${typeName}Signers = (${eitherSignerAccounts.join(' | ')})[];\n\n`;
    }

    // Resolvers type (only when resolverValueNode exists)
    const resolverNames = collectResolverNames(ix);
    if (resolverNames.size > 0) {
        const resolversTypeName = `${typeName}Resolvers`;
        output += `export type ${resolversTypeName} = {\n`;
        for (const name of resolverNames) {
            output += `    ${name}: ResolverFn<${argsRef === 'void' ? 'Record<string, unknown>' : argsRef}, ${accountsInterfaceName}>;\n`;
        }
        output += '};\n\n';
    }

    return output;
}

/**
 * Convert Codama type to TypeScript type string.
 */
export function codamaTypeToTS(type: TypeNode | undefined, definedTypes: DefinedTypeNode[]): string {
    if (!type || typeof type !== 'object') return 'unknown';

    switch (type.kind) {
        case 'numberTypeNode':
            return ['u64', 'u128', 'i64', 'i128'].includes(type.format ?? '') ? 'number | bigint' : 'number';
        case 'publicKeyTypeNode':
            return 'Address';
        case 'stringTypeNode':
            return 'string';
        case 'booleanTypeNode':
            return 'boolean';
        case 'optionTypeNode':
            return `${codamaTypeToTS(type.item, definedTypes)} | null`;
        case 'remainderOptionTypeNode':
        case 'zeroableOptionTypeNode':
            return `${codamaTypeToTS(type.item, definedTypes)} | null`;
        case 'bytesTypeNode':
            return 'Uint8Array';
        case 'fixedSizeTypeNode':
        case 'sizePrefixTypeNode':
        case 'hiddenPrefixTypeNode':
        case 'preOffsetTypeNode':
        case 'postOffsetTypeNode':
        case 'hiddenSuffixTypeNode':
        case 'sentinelTypeNode':
            return codamaTypeToTS(type.type, definedTypes);
        case 'amountTypeNode':
        case 'solAmountTypeNode':
            return 'number | bigint';
        case 'structTypeNode': {
            if (!type.fields || type.fields.length === 0) return '{}';
            const fields = type.fields
                .filter(f => f.defaultValueStrategy !== 'omitted')
                .map(f => `${f.name}: ${codamaTypeToTS(f.type, definedTypes)}`);
            if (fields.length === 0) return '{}';
            return `{ ${fields.join('; ')} }`;
        }
        case 'enumTypeNode': {
            if (!type.variants || type.variants.length === 0) return 'unknown';
            const allEmpty = type.variants.every(v => v.kind === 'enumEmptyVariantTypeNode');
            if (allEmpty) {
                return type.variants.map(v => `'${v.name}'`).join(' | ');
            }
            const variantTypes = type.variants.map(v => {
                if (v.kind === 'enumEmptyVariantTypeNode') {
                    return `{ __kind: '${v.name}' }`;
                }
                if (v.kind === 'enumStructVariantTypeNode' && v.struct) {
                    const inner = codamaTypeToTS(v.struct, definedTypes);
                    return `{ __kind: '${v.name}' } & ${inner}`;
                }
                if (v.kind === 'enumTupleVariantTypeNode' && v.tuple) {
                    const inner = codamaTypeToTS(v.tuple, definedTypes);
                    return `{ __kind: '${v.name}'; fields: ${inner} }`;
                }
                return `{ __kind: '${v.name}' }`;
            });
            return variantTypes.join(' | ');
        }
        case 'tupleTypeNode': {
            if (!type.items || type.items.length === 0) return '[]';
            const items = type.items.map(i => codamaTypeToTS(i, definedTypes));
            return `[${items.join(', ')}]`;
        }
        case 'arrayTypeNode':
        case 'setTypeNode': {
            const itemType = codamaTypeToTS(type.item, definedTypes);
            const needsParens = itemType.includes(' | ') || itemType.includes(' & ');
            return needsParens ? `(${itemType})[]` : `${itemType}[]`;
        }
        case 'mapTypeNode': {
            const v = codamaTypeToTS(type.value, definedTypes);
            return `Record<string, ${v}>`;
        }
        case 'definedTypeLinkNode': {
            if (!type.name) return 'unknown';
            const def = definedTypes.find(d => d.name === type.name);
            if (!def) return 'unknown';
            return codamaTypeToTS(def.type, definedTypes);
        }
        case 'dateTimeTypeNode': {
            return codamaTypeToTS(type.number, definedTypes);
        }
        default:
            type['kind'] satisfies never;
            return 'unknown';
    }
}

/**
 * Collects all unique resolverValueNode names from an instruction's accounts and arguments.
 */
export function collectResolverNames(ix: InstructionNode): Set<string> {
    const names = new Set<string>();

    function extractResolverNodeName(node: InstructionInputValueNode | undefined): void {
        if (!node) return;
        if (node.kind === 'resolverValueNode' && node.name) {
            names.add(node.name);
        } else if (node.kind === 'conditionalValueNode') {
            extractResolverNodeName(node.condition);
            extractResolverNodeName(node.ifTrue);
            extractResolverNodeName(node.ifFalse);
        }
    }

    for (const acc of ix.accounts) {
        extractResolverNodeName(acc.defaultValue);
    }
    for (const arg of ix.arguments) {
        extractResolverNodeName(arg.defaultValue);
    }

    return names;
}

/**
 * Determines if an account has an auto-resolvable default value.
 * Accounts with payerValueNode or identityValueNode defaults require
 * explicit input and are NOT auto-resolvable.
 */
export function isAccountAutoResolvable(acc: InstructionAccountNode): boolean {
    const nonResolvableValueNodes = ['payerValueNode', 'identityValueNode'];
    if (acc.defaultValue == null) return false;
    return !nonResolvableValueNodes.includes(acc.defaultValue.kind);
}
