import {
    collectResolverNames,
    generateInstructionTypes as generateArgsAccountsResolvers,
} from '@codama/dynamic-address-resolution/codegen';
import { type InstructionNode, pascalCase, type RootNode } from 'codama';

export const INSTRUCTION_TYPES_FILE_HEADER = `/**
 * Auto-generated instruction types
 * DO NOT EDIT - Generated by @codama/dynamic-instructions generate-instruction-types
 */

import type { Address } from '@solana/addresses';
import type { InstructionsBuilderFn, ResolverFn } from '@codama/dynamic-instructions';

`;

/**
 * Generate the per-instruction `${Name}Signers` type alias for instructions with `isSigner: 'either'` accounts.
 */
export function generateSignerTypes(idl: RootNode): string {
    let output = '';
    for (const ix of idl.program.instructions) {
        output += generateSignersTypeBlock(ix);
    }
    return output;
}

/**
 * Generate the `${Program}InstructionBuilders` aggregate map type.
 * Keys each instruction name to its `InstructionsBuilderFn` signature.
 */
export function generateInstructionBuildersMap(idl: RootNode): string {
    const programName = pascalCase(idl.program.name);
    let output = `/**
 * Strongly-typed instruction builders for ${programName}.
 */
export type ${programName}InstructionBuilders = {\n`;

    for (const ix of idl.program.instructions) {
        const typeName = pascalCase(ix.name);
        const eitherSignerAccounts = ix.accounts.filter(acc => acc.isSigner === 'either');
        const resolverNames = collectResolverNames(ix);

        const signersGeneric = eitherSignerAccounts.length > 0 ? `${typeName}Signers` : 'string[]';
        const args = ix.arguments.filter(arg => arg.defaultValueStrategy !== 'omitted');
        const remainingAccountArgs = (ix.remainingAccounts ?? []).filter(ra => ra.value.kind === 'argumentValueNode');
        const hasArgs = args.length > 0 || remainingAccountArgs.length > 0;
        const argsGeneric = hasArgs ? `${typeName}Args` : 'void';
        const accountsGeneric = `${typeName}Accounts`;
        const resolversGeneric = resolverNames.size > 0 ? `, ${typeName}Resolvers` : '';

        output += `    ${ix.name}: InstructionsBuilderFn<${argsGeneric}, ${accountsGeneric}, ${signersGeneric}${resolversGeneric}>;\n`;
    }

    output += '};\n';
    return output;
}

/**
 * Compose the full instruction-types output: dar's Args/Accounts/Resolvers
 * blocks + Signers + InstructionBuilders aggregate map. Used by the `di` CLI
 * to emit a standalone file (paired with `INSTRUCTION_TYPES_FILE_HEADER`).
 */
export function generateInstructionTypes(idl: RootNode): string {
    return generateArgsAccountsResolvers(idl) + generateSignerTypes(idl) + generateInstructionBuildersMap(idl);
}

function generateSignersTypeBlock(ix: InstructionNode): string {
    const eitherSignerAccounts = ix.accounts.filter(acc => acc.isSigner === 'either').map(acc => `'${acc.name}'`);
    if (eitherSignerAccounts.length === 0) return '';
    const typeName = pascalCase(ix.name);
    return `export type ${typeName}Signers = (${eitherSignerAccounts.join(' | ')})[];\n\n`;
}
