import type { RootNode } from 'codama';

import { generateInstructionTypes } from './generate-instruction-types';
import { generatePdaTypes } from './generate-pda-types';

/**
 * Generate a self-contained TypeScript file with all address-resolution types for a Codama IDL:
 * - PDA seed types, `${Program}Pdas` map,
 * - Per-instruction `${Name}Args`, `${Name}Accounts`, `${Name}Resolvers`.
 */
export function generateTypes(idl: RootNode): string {
    const { typeBlock: pdaBlock, mapTypeName } = generatePdaTypes(idl);
    return getTypesFileHeader(mapTypeName !== null) + pdaBlock + generateInstructionTypes(idl);
}

const getTypesFileHeader = (importPdaTypes: boolean): string => {
    const addressImports = importPdaTypes ? 'Address, ProgramDerivedAddress' : 'Address';
    return `/**
 * Auto-generated address-resolution types
 * DO NOT EDIT - Generated by @codama/dynamic-address-resolution generate-types
 */

import type { ${addressImports} } from '@solana/addresses';

export type ResolverFn<
    TArgumentsInput = Record<string, unknown>,
    TAccountsInput = Record<string, unknown>
> = (argumentsInput: TArgumentsInput, accountsInput: TAccountsInput) => Promise<unknown>;

`;
};
