import { OPTIONAL_NODE_KINDS } from '@codama/dynamic-address-resolution';
import {
    collectResolverNames,
    generateInstructionTypes,
    generatePdaTypes,
} from '@codama/dynamic-address-resolution/codegen';
import { generateSignerTypes } from '@codama/dynamic-instructions/codegen';
import { pascalCase, type RootNode } from 'codama';

/**
 * Generate TypeScript type for program client.
 */
export function generateClientTypes(idl: RootNode): string {
    const programName = pascalCase(idl.program.name);

    const { mapTypeName: pdasMapTypeName, typeBlock: pdaTypeBlock } = generatePdaTypes(idl);
    const hasPdas = pdasMapTypeName !== null;
    const addressImports = hasPdas ? 'Address, ProgramDerivedAddress' : 'Address';

    let output = `/**
 * Auto-generated types for strongly-typed ProgramClient
 * DO NOT EDIT - Generated by @codama/dynamic-client generate-client-types
 *
 * Note: When the IDL contains types that cannot be resolved (e.g. unsupported
 * kind, missing definition), argument types fall back to \`unknown\` instead of
 * \`any\`. Consumers should narrow these values before use.
 */

import type { InstructionNode, RootNode } from 'codama';
import type { ${addressImports} } from '@solana/addresses';
import type { Instruction } from '@solana/instructions';

export type ResolverFn<
    TArgumentsInput = Record<string, unknown>,
    TAccountsInput = Record<string, unknown>
> = (argumentsInput: TArgumentsInput, accountsInput: TAccountsInput) => Promise<unknown>;

/**
 * Method builder interface.
 */
export type MethodBuilder<TAccounts, TSigners extends string[], TResolvers = Record<string, never>> = {
    accounts(accounts: TAccounts): MethodBuilder<TAccounts, TSigners, TResolvers>;
    resolvers(resolvers: Partial<TResolvers>): MethodBuilder<TAccounts, TSigners, TResolvers>;
    signers(signers: TSigners): MethodBuilder<TAccounts, TSigners, TResolvers>;
    instruction(): Promise<Instruction>;
};

`;

    output += generateInstructionTypes(idl);
    output += generateSignerTypes(idl);

    for (const ix of idl.program.instructions) {
        const typeName = pascalCase(ix.name);
        const args = ix.arguments.filter(arg => arg.defaultValueStrategy !== 'omitted');
        const remainingAccountArgs = (ix.remainingAccounts ?? []).filter(ra => ra.value.kind === 'argumentValueNode');
        const hasArgs = args.length > 0 || remainingAccountArgs.length > 0;
        const argsRef = hasArgs ? `${typeName}Args` : 'void';
        const accountsRef = `${typeName}Accounts`;
        const eitherSignerCount = ix.accounts.filter(acc => acc.isSigner === 'either').length;
        const signersGeneric = eitherSignerCount > 0 ? `${typeName}Signers` : 'string[]';
        const resolversRef = collectResolverNames(ix).size > 0 ? `${typeName}Resolvers` : '';

        const hasRequiredArgs = args.some(arg => !OPTIONAL_NODE_KINDS.includes(arg.type.kind));
        const hasRequiredRemainingAccounts = remainingAccountArgs.some(ra => !ra.isOptional);
        const allArgsOptional = !hasRequiredArgs && !hasRequiredRemainingAccounts;
        const argsParam = argsRef === 'void' ? '' : allArgsOptional ? `args?: ${argsRef}` : `args: ${argsRef}`;
        const resolversGeneric = resolversRef ? `, ${resolversRef}` : '';
        const methodSignature = `(${argsParam}) => MethodBuilder<${accountsRef}, ${signersGeneric}${resolversGeneric}>`;
        output += `export type ${typeName}Method = ${methodSignature};\n\n`;
    }

    output += `/**
 * Strongly-typed methods for ${programName}.
 */
export type ${programName}Methods = {\n`;

    for (const ix of idl.program.instructions) {
        const typeName = pascalCase(ix.name);
        output += `    ${ix.name}: ${typeName}Method;\n`;
    }

    output += '};\n\n';

    output += pdaTypeBlock;

    const pdasProp = pdasMapTypeName ? `    pdas: ${pdasMapTypeName};\n` : '';
    output += `/**
 * Strongly-typed program client for ${programName}.
 */
export type ${programName}ProgramClient = {
    methods: ${programName}Methods;
${pdasProp}    programAddress: Address;
    root: RootNode;
    instructions: Map<string, InstructionNode>;
};
`;

    return output;
}
